apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: opni-upgrade-responder-client
spec: # CronJob
  schedule: "0 * * * *"
  jobTemplate:
    spec: # JOB
      template:
        spec: # Pod
          containers:
          - image: alpine
            env:
            - name: SERVER_URL
              value: "http://opni-upgrade-responder.default.svc.cluster.local:8314"
            command: ["/bin/sh","-c"]
            args: ["apk add curl && apk add coreutils && curl -X POST $SERVER_URL/v1/checkupgrade -d '{ \"appVersion\": \"v0.11.11\", \"extraInfo\": {}}'"]
            name: opni-upgrade-responder-client
          restartPolicy: OnFailure
      backoffLimit: 2
